### ISSUE TITLE
 ERROR  resolvePDFJS is not a function

### ISSUE THREAD

**Issue by cosbgn** [unjs/unpdf#18]
### Environment

 ERROR  resolvePDFJS is not a function happens on the lastest v0.12 - v11 works fine

### Reproduction

import { extractText, getDocumentProxy } from "unpdf";

### Describe the bug

 ERROR  resolvePDFJS is not a function

**Comment by cosbgn** [comment]
deleting node_modules fixed it. Sorry for bothering.

**Comment by johannschopplich** [comment]
Probably the dependency wasn't up to date. Thanks for checking!

**Comment by parhammmm** [comment]
@johannschopplich this actually is a valid issue, I had to use the following to get things working, even though I'm not using a serverless environment. I'm not quite sure what's caused the issue. 


```ts
    await configureUnPDF({
      pdfjs: () => import("pdfjs-serverless"),
    });
```

**Comment by parhammmm** [comment]
@johannschopplich can confirm the fix works

**Comment by yslflow** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by johannschopplich** [comment]
Thanks a lot for confirming it! Closing it, since resolved.
