### ISSUE TITLE
ERROR resolvePDFJS is not a function

### ISSUE THREAD

**Issue by parhammmm** [unjs/unpdf#19]
### Environment

Node: v22.2.0
NextJS: 14.2.13
unpdf: v0.12.0

### Reproduction

`import { extractText, getDocumentProxy } from "unpdf";`

### Describe the bug

(note pdfjs was installed)

```shell
TypeError: resolvePDFJS is not a function
    at resolvePDFJSImports (node_modules/unpdf/dist/index.mjs:41:28)
    at async getResolvedPDFJS (node_modules/unpdf/dist/index.mjs:17:5)
    at async getDocumentProxy (node_modules/unpdf/dist/index.mjs:5:27)

```

### Additional context

follow up from https://github.com/unjs/unpdf/issues/18

Adding the following fixes the issue:

```ts
await configureUnPDF({
  pdfjs: () => import("pdfjs-serverless"),
});
```

This doesn't fix it
```ts
await configureUnPDF({
  // Use the official PDF.js build (make sure to install it first)
  pdfjs: () => import("pdfjs-dist"),
});
```

**Comment by johannschopplich** [comment]
You're right, there was a bug indeed! Instead of the inlined dynamic import, the serverless build couldn't be loaded correctly. This will be fixed in the next version.

Thanks for the report!

**Comment by parhammmm** [comment]
@johannschopplich awesome! thank you for the quick fix :)
