### ISSUE TITLE
Struggling to get it to work in a Supabase Edge Function

### ISSUE THREAD

**Issue by joshling1919** [unjs/unpdf#3]
### Environment

Using via esm: https://esm.sh/unpdf@0.10.0/
Deno version: 1.38.4 (I'm guessing this because it's not easy to see the supabase edge function environment, but [they say they use the latest stable version](https://github.com/supabase/cli/issues/490#issuecomment-1263104657).

### Reproduction

Sorry, it's a bit hard to reproduce since it's only failing in the deployed Supabase edge function. When I run it locally in my docker container, it works fine. Here's the relevant code though of my edge function:

```ts
import { configureUnPDF, getResolvedPDFJS } from 'https://esm.sh/unpdf@0.10.0';
import * as pdfjs from 'https://esm.sh/unpdf@0.10.0/dist/pdfjs.mjs';

configureUnPDF({
  // deno-lint-ignore require-await
  pdfjs: async () => pdfjs,
});
const resolvedPdfJs = await getResolvedPDFJS();
const { getDocument } = resolvedPdfJs;

export async function convertPdfToText(
  arrayBuffer: ArrayBuffer
): Promise<string> {
  try {
    const data = new Uint8Array(arrayBuffer);

    // Get the document
    const doc = await getDocument(data).promise;
    let allText = '';

    // Iterate through each page of the document
    for (let i = 1; i <= doc.numPages; i++) {
      const page = await doc.getPage(i);
      const textContent = await page.getTextContent();

      // Combine the text items with a space (adjust as needed)
      const pageText = textContent.items
        .map((item) => {
          if ('str' in item) {
            return item.str;
          }
          return '';
        })
        .join(' ');
      allText += pageText + '\n'; // Add a newline after each page's text
    }

    return allText;
  } catch (error) {
    console.error('Error converting PDF to text', error);
    throw error;
  }
}
```

### Describe the bug

In the supabase edge functions log, it consistently throws this error:

```
event loop error: Error: PDF.js is not available. Please add the package as a dependency.
    at f (https://esm.sh/v135/unpdf@0.10.0/deno/unpdf.mjs:2:574)
    at async h (https://esm.sh/v135/unpdf@0.10.0/deno/unpdf.mjs:2:230)
    at async file:///home/runner/work/tl.ai/tl.ai/supabase/functions/process/index.ts:12:23
```

Originally, I followed the base setup instructions. Then, I tried to use `getResolvedPDFJS`. Finally, I tried to first `configureUnPDF` and pointing `pdfjs` specifically to the one exported from your package. However, all still failed in the production environment. 

I'm mainly wondering if I'm not following the instructions correctly for configuring pdfjs. Thanks in advance for your help!

**Comment by joshling1919** [comment]
Ah, turns out I forgot to put an `await` before `configureUnPDF`. It works now! 🎉 Thank you so much!

**Comment by johannschopplich** [comment]
Glad you found the solution!

**Comment by shergillmanav19** [comment]
Was struggling with this, thank you so much!! @joshling1919
