### ISSUE TITLE
Unpdf can't render pages with images

### ISSUE THREAD

**Issue by DemoMacro** [unjs/unpdf#4]
### Environment

Node.js v20.9.0
PNPM v8.10.0
UnPDF v0.10.0

### Reproduction

Example Code: [CodeSandBox](https://codesandbox.io/p/devbox/unpdf-cant-render-pages-with-images-44hqfw?embed=1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqkajwnh00063j6ftvzfrdr3%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqkajwng00023j6fjiylar9x%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqkajwnh00043j6fa5cj9e8f%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqkajwnh00053j6f41wk8f3y%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B100%252C0%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqkajwng00023j6fjiylar9x%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqkajwng00013j6fc058hgzx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clqkajwng00023j6fjiylar9x%2522%252C%2522activeTabId%2522%253A%2522clqkajwng00013j6fc058hgzx%2522%257D%252C%2522clqkajwnh00053j6f41wk8f3y%2522%253A%257B%2522id%2522%253A%2522clqkajwnh00053j6f41wk8f3y%2522%252C%2522activeTabId%2522%253A%2522clqkar26t00ma3j6ehiip4hs6%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522SANDBOX_INFO%2522%252C%2522id%2522%253A%2522clqkar26t00ma3j6ehiip4hs6%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clqkajwnh00043j6fa5cj9e8f%2522%253A%257B%2522id%2522%253A%2522clqkajwnh00043j6fa5cj9e8f%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqkaoucr00f93j6e360wuxt7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clqkaoula0007efg82y8v6zsu%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqkaoucr00f93j6e360wuxt7%2522%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Describe the bug

When I am ready to render a page with unpdf, renderPageAsImage will report an error if there is an image embedded in the pdf.

### Logs

```sh
TypeError: r.createCanvas is not a function
    at NodeCanvasFactory._createCanvas (file:///workspaces/workspace/node_modules/.pnpm/unpdf@0.10.0/node_modules/unpdf/dist/pdfjs.mjs:1:1316062)
    at NodeCanvasFactory.create (file:///workspaces/workspace/node_modules/.pnpm/unpdf@0.10.0/node_modules/unpdf/dist/pdfjs.mjs:1:1153693)
    at CachedCanvases.getCanvas (file:///workspaces/workspace/node_modules/.pnpm/unpdf@0.10.0/node_modules/unpdf/dist/pdfjs.mjs:1:1163909)
    at CanvasGraphics.paintInlineImageXObject (file:///workspaces/workspace/node_modules/.pnpm/unpdf@0.10.0/node_modules/unpdf/dist/pdfjs.mjs:1:1198408)
    at CanvasGraphics.paintImageXObject (file:///workspaces/workspace/node_modules/.pnpm/unpdf@0.10.0/node_modules/unpdf/dist/pdfjs.mjs:1:1197232)
    at CanvasGraphics.executeOperatorList (file:///workspaces/workspace/node_modules/.pnpm/unpdf@0.10.0/node_modules/unpdf/dist/pdfjs.mjs:1:1172983)
    at InternalRenderTask._next (file:///workspaces/workspace/node_modules/.pnpm/unpdf@0.10.0/node_modules/unpdf/dist/pdfjs.mjs:1:1152632)
```

**Comment by johannschopplich** [comment]
Thanks a lot for the reproduction. Merry Christmas, still! 🎄
