### ISSUE TITLE
PDF Generator 

### ISSUE THREAD

**Issue by Celibioux** [unjs/unpdf#9]
### Describe the feature

It would be nice addon a PDF Generator (something like adding pdf-lib ) 

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by edimitchel** [comment]
That's a great idea which is an opportunity for unpdf to gain in value. 

Writing and reading pdf, what a good masterpiece it could become !
cc @pi0

**Comment by Rados51** [comment]
[jspdf](https://www.npmjs.com/package/jspdf) works fine in CF Workers, so that could be one way.

**Comment by johannschopplich** [comment]
unpdf's scope is PDF parsing, not generation. Maybe that will change in the distant future. But it's out of scope for now.
